### PR TITLE
fix: special characters handling.

### LINKED ISSUE #10: Not working with special characters like `===`
Hi

I use alternate-toggler with NVIM v0.8.0.
I have added a rule to toggle `===` to `!==` the way you have commented [here](https://github.com/rmagatti/alternate-toggler/issues/6#issuecomment-1235711003).

This does work for normal characters like in `yes` and `no` but not in "special" characters like `===` or `!==`.

The reason for that is that [`<cword>`](https://github.com/rmagatti/alternate-toggler/blob/5575312b949ca5991afa3807175919a0fb448afe/plugin/alternate-toggler.vim#L9) by default does not capture these characters, instead it seems to capture the next valid characters.

```txt
							*word*
A word consists of a sequence of letters, digits and underscores, or a
sequence of other non-blank characters, separated with white space (spaces,
tabs, <EOL>).  This can be changed with the 'iskeyword' option.  An empty line
is also considered to be a word.
							*WORD*
A WORD consists of a sequence of non-blank characters, separated with white
space.  An empty line is also considered to be a WORD.
```

toggle

### PR DESCRIPTION
**Pull request by rmagatti**
Thanks to @schoero for pointing out how the plugin was not working for alternating between special characters like `===` `!==`. This commit takes what he's done in [this PR](https://github.com/rmagatti/alternate-toggler/pull/12) and moves it into Lua code instead of Vimscript.

I have also made a few improvements that include:
- Improving the readme with install data for Packer.nvim;
- Adding a `setup` function for configuring custom alternates from Lua;
- Fixed the jarring cursor changing positions when alternating. This was happening because of how ciw works. All I did was save the cursor position before making the change then setting it again after the change is done;
- Fixed the xpcall parameters;
- Add `===` `!==` alternates to the default table.

This commit fixes #10.

### CODE REVIEW

File: lua/alternate-toggler.lua [hunk 1]
```diff
@@ -1,22 +1,22 @@
...
+	["YES"] = "NO",
+	["1"] = "0",
+	["<"] = ">",
+	["("] = ")",
+	["["] = "]",
+	["{"] = "}",
+	['"'] = "'",
+	['""'] = "''",
+	["+"] = "-",
+	["==="] = "!==",
```
Comment (schoero) [inline lua/alternate-toggler.lua:17]: You could also include `==` by default.
